import { FaBed } from "react-icons/fa";
import { GiBathtub } from "react-icons/gi";
import { MdOutlineSquareFoot } from "react-icons/md";
import { BsLinkedin } from "react-icons/bs";
import { AiOutlineTwitter } from "react-icons/ai";
import { AiFillInstagram } from "react-icons/ai";
import { BsFacebook } from "react-icons/bs";

export const partment = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const vill = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const family = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const studio = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const condo = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const shop = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const multi = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const lot = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const offices = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const owl = [
  {
    image: "./assets/room1.webp",
    name: "Villa in Coral Amarilo ",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House7",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Family Home",
  },
  {
    image: "./assets/York1.jpg",
    name: "Villa in Window View",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House4",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Family Home",
  },
  {
    image: "./assets/rancho1.webp",
    name: "5225 Greenwhich Pike",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House14",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Family Home",
  },
  {
    image: "./assets/officee1.webp",
    name: "Avinguda Diagonal",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House21",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Modern Offices",
  },
  {
    image: "./assets/malibu1.webp",
    name: "5225 NorthEste ",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House12",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Multi-Family Home",
  },
  {
    image: "./assets/buffalo1.webp",
    name: "5884 Gudme ",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House9",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Multi-Family Home",
  },
  {
    image: "./assets/officeg1.webp",
    name: "Avinguda Diagonal",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House23",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Mordern Office",
  },
  {
    image: "./assets/horse1.webp",
    name: "Greenwhich Pike",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House11",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Ranch & Farm",
  },
];
export const agent = [
  {
    name: "Karen Masterson",
    position: "Chief Legal Officer",
    description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/agent1.jpeg",
    action: "View Profile",
    link: "./Profile1",
    iconOne: <BsFacebook />,
    iconTwo: <AiOutlineTwitter />,
    iconThree: <AiFillInstagram />,
    iconFour: <BsLinkedin />,
    socialOne: "https://www.facebook.com",
    socialTwo: "https://www.twitter.com",
    socialThree: "https://www.instagram.com",
    socialFour: "https://www.linkedin.com",
  },
  {
    name: "Kathleem Myers",
    position: "Chief Operating Officer",
    description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/agent2.jpeg",
    action: "View Profile",
    link: "./Profile2",
    iconOne: <BsFacebook />,
    iconTwo: <AiOutlineTwitter />,
    iconThree: <AiFillInstagram />,
    iconFour: <BsLinkedin />,
    socialOne: "https://www.facebook.com",
    socialTwo: "https://www.twitter.com",
    socialThree: "https://www.instagram.com",
    socialFour: "https://www.linkedin.com",
  },
  {
    name: "John Loyd",
    position: "Cheif Analytics Officer",
    description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/agent5.jpeg",
    action: "View Profile",
    link: "./Profile3",
    iconOne: <BsFacebook />,
    iconTwo: <AiOutlineTwitter />,
    iconThree: <AiFillInstagram />,
    iconFour: <BsLinkedin />,
    socialOne: "https://www.facebook.com",
    socialTwo: "https://www.twitter.com",
    socialThree: "https://www.instagram.com",
    socialFour: "https://www.linkedin.com",
  },
  {
    name: "Jennifer Barton",
    position: "Vice President, Product",
    description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: "./assets/agent6.jpeg",
    action: "View Profile",
    link: "./Profile4",
    iconOne: <BsFacebook />,
    iconTwo: <AiOutlineTwitter />,
    iconThree: <AiFillInstagram />,
    iconFour: <BsLinkedin />,
    socialOne: "https://www.facebook.com",
    socialTwo: "https://www.twitter.com",
    socialThree: "https://www.instagram.com",
    socialFour: "https://www.linkedin.com",
  },
];
export const partners = [
  {
    image: "./assets/part1.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part2.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part3.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part4.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part5.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part6.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part7.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part8.png",
    className: "d-block w-100",
  },
  {
    image: "./assets/part9.png",
    className: "d-block w-100",
  },
];
export const review = [
  {
    image: "./assets/say1.jpeg",
    name: "Searcy Michael",
    position: "Author",
    description:
      "I have to say how much I love the artistry and creativity that goes into these places. They are all truly unique and I love each and every one of the ideas for all different reasons. Nicely done video. Thanks for posting.",
  },
  {
    image: "./assets/say2.jpeg",
    name: "Maria Flyn",
    position: "Manager at Hottubs Inc.",
    description:
      "This house looks even more stunning than the one presented at the main channel. What a change does it make for a house when you integrate both architectural style with the furniture and the appliances! It is absolutely marvelous.",
  },
  {
    image: "./assets/say3.jpeg",
    name: "Filman Lamina",
    position: "Manager at Lawn LTD.",
    description:
      " I love how they have hidden all the industrial equipment such as the pool's filtration systems, AC's compressor units, etc. which you usually find on the rooftop. This house is well-thought out, sleek and beautifully designed. A truly home resort feel.",
  },
  {
    image: "./assets/say4.jpeg",
    name: "Andreea Houston",
    position: "Actress",
    description:
      " Out of all the AMAZING natural elements that nature brings to the table, I'm gratified to hear that you and Micky have back problems! Back to the relm of the human...and I say this in the kindest sort of way...love your channel",
  },
  {
    image: "./assets/say5.jpeg",
    name: "Larry Eckerdt",
    position: "Doctor, Higway Nursing Home.",
    description:
      "  Beautiful home, great tour and photography! Perfect size in my opinion- some of the largest homes lose their soul. This has the amenities a luxury home requires, without having to  make up reasons for excess spaces. My dogs would love the yard!",
  },
  {
    image: "./assets/say6.jpeg",
    name: "Hannah Mae Endaya",
    position: "HRM, Higway Nursing Home.",
    description:
      " It's so gorgeous 🥺 I love the open shelving on the bbq area and the lights are amazing, the house is super nice 😍 good job guys",
  },
];
