import { FaBed } from "react-icons/fa";
import { GiBathtub } from "react-icons/gi";
import { MdOutlineSquareFoot } from "react-icons/md";

export const partment = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const vill = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const family = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const studio = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const condo = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const shop = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const multi = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const lot = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const offices = [
  {
    image: "./assets/horse1.webp",
    name: "Modern Apartment",
    bed: "3",
    bath: "2",
    size: "1200 SQ FT",
    description: "Phase13, Thika",
    link: "../House11",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$1550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/castle1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House10",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/whity1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Kisumu",
    link: "../House16",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/rancho1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House14",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/house1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House6",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/bed1.jpg",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Thika",
    link: "../House2",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/room1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Nairobi",
    link: "../House7",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
  {
    image: "./assets/ocean1.webp",
    name: "Modern Apartment",
    bed: "10",
    bath: "10",
    size: "1800 SQ FT",
    description: "Mombasa",
    link: "../House13",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    price: "$2550",
    action: "View",
    boxText: "Apartment",
  },
];
export const owl = [
  {
    image: "./assets/room1.webp",
    name: "Villa in Coral Amarilo ",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House7",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Family Home",
  },
  {
    image: "./assets/York1.jpg",
    name: "Villa in Window View",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House4",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Family Home",
  },
  {
    image: "./assets/rancho1.webp",
    name: "5225 Greenwhich Pike",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House14",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Family Home",
  },
  {
    image: "./assets/officee1.webp",
    name: "Avinguda Diagonal",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House21",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Modern Offices",
  },
  {
    image: "./assets/malibu1.webp",
    name: "5225 NorthEste ",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House12",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Multi-Family Home",
  },
  {
    image: "./assets/buffalo1.webp",
    name: "5884 Gudme ",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House9",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Multi-Family Home",
  },
  {
    image: "./assets/officeg1.webp",
    name: "Avinguda Diagonal",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House23",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Mordern Office",
  },
  {
    image: "./assets/horse1.webp",
    name: "Greenwhich Pike",
    price: "$1550",
    boxText: "Featured",
    action: "View",
    link: "../House11",
    bed: "4",
    bath: "3",
    size: "1200 Sq Ft",
    iconOne: <FaBed />,
    iconTwo: <GiBathtub />,
    iconThree: <MdOutlineSquareFoot />,
    type: "Ranch & Farm",
  },
];
