import { BsDot } from "react-icons/bs";
export const rent = [
  {
    link: "/House1",
    image: "./assets/me1.jpg",
    form: "Rent",
    name: "9631 North Bridle",
    price: "$1400",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House2",
    image: "./assets/bed1.jpg",
    form: "Rent",
    name: "Leverton Cove Road, MA 01069",
    price: "$2600",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House3",
    image: "./assets/new1.webp",
    form: "Rent",
    name: "North Drive East Bridgewater, MA 05897",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House4",
    image: "./assets/York1.jpg",
    form: "Rent",
    name: "North Drive East Bridgewater, MA 05897",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House5",
    image: "./assets/view1.jpg",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1550",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House6",
    image: "./assets/house1.webp",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House7",
    image: "./assets/room1.webp",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House8",
    image: "./assets/tig1.webp",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
];
