import { BsDot } from "react-icons/bs";
export const rent = [
  {
    link: "/House1",
    image: "./assets/me1.jpg",
    form: "Rent",
    name: "9631 North Bridle",
    price: "$1400",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House2",
    image: "./assets/bed1.jpg",
    form: "Rent",
    name: "Leverton Cove Road, MA 01069",
    price: "$2600",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House3",
    image: "./assets/new1.webp",
    form: "Rent",
    name: "North Drive East Bridgewater, MA 05897",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House4",
    image: "./assets/York1.jpg",
    form: "Rent",
    name: "North Drive East Bridgewater, MA 05897",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House5",
    image: "./assets/view1.jpg",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1550",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House6",
    image: "./assets/house1.webp",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House7",
    image: "./assets/room1.webp",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/House8",
    image: "./assets/tig1.webp",
    form: "Rent",
    name: "Leverton Cove Road, MA 01337",
    price: "$1250",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous9",
    image: "./assets/buffalo1.webp",
    form: "Rent",
    name: "Gudme, Denmark",
    price: "$8000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous10",
    image: "./assets/castle1.webp",
    form: "Rent",
    name: "Lexington, United States",
    price: "$25,000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous11",
    image: "./assets/horse1.webp",
    form: "Rent",
    name: "Merna,United States",
    price: "$32,000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous12",
    image: "./assets/malibu1.webp",
    form: "Rent",
    name: "Bodhei,MBS,40511 Kenya",
    price: "$2,000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous13",
    image: "./assets/ocean1.webp",
    form: "Rent",
    name: "Kisumu,ksm, Kenya",
    price: "$32,000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous14",
    image: "./assets/rancho1.webp",
    form: "Rent",
    name: "Beaufort,BW,4201 South Africa",
    price: "$29,000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous15",
    image: "./assets/roma1.webp",
    form: "Rent",
    name: "Yembe,YM,1100 Angola",
    price: "$18,000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous16",
    image: "./assets/whity1.webp",
    form: "Rent",
    name: "Al Akrad,KY,5110 United Egypt",
    price: "$27,000",
    bed: "5Beds",
    bath: "5Bathrooms",
    size: "4,558 SQ FT",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous17",
    image: "./assets/officea1.jpg",
    form: "Rent",
    name: "10013, New York City",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous18",
    image: "./assets/officeb1.jpg",
    form: "Rent",
    name: "40900, Bogota",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous19",
    image: "./assets/officec1.webp",
    form: "Rent",
    name: "8900, Guadalajara",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous20",
    image: "./assets/officed1.webp",
    form: "Rent",
    name: "9008, Houston",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous21",
    image: "./assets/officee1.webp",
    form: "Rent",
    name: "4009, Moscow",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous22",
    image: "./assets/officef1.webp",
    form: "Rent",
    name: "4059, Lisbon",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous23",
    image: "./assets/officeg1.webp",
    form: "Rent",
    name: "30044, Nairobi",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
  {
    link: "/Hous24",
    image: "./assets/officeh1.webp",
    form: "Rent",
    name: "10013, Madrid",
    price: "$7,000",
    bed: " Private Workspace",
    bath: " Flexible Terms",
    size: " Fast-Move-In",
    small: "Marketed By Vargas Camino's International Realty",
    iconOne: <BsDot />,
  },
];
